
file_header="/*****************************************************************************
 * Copyright (C) Queen's University Belfast, ECIT, 2017                      *
 *                                                                           *
 * This file is part of libsafecrypto.                                       *
 *                                                                           *
 * This file is subject to the terms and conditions defined in the file      *
 * 'LICENSE', which is part of this source code package.                     *
 *****************************************************************************/

/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 *
 * Git commit information:
 *   Author: $SC_AUTHOR$
 *   Date:   $SC_DATE$
 *   Branch: $SC_BRANCH$
 *   Id:     $SC_IDENT$
 */


"

file_header_2="#include \"utils/arith/ntt.h\"
#ifndef USE_RUNTIME_NTT_TABLES
#include \"utils/arith/ntt_tables.h\"
#endif
#include \"utils/arith/sc_math.h\"
#include <stdio.h>

"

file_header_3="#pragma once

#include \"safecrypto_types.h\"
#include \"utils/arith/limb.h\"


"

# Generate the C implementation files

$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="reference" -D_ENABLE_REFERENCE -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_2" >> top.txt
echo "#include \"utils/arith/ntt_reference.h\"" >> top.txt
echo "" >> top.txt
echo "" >> top.txt
cat top.txt bot.txt > ntt_reference.c

$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="barrett" -D_ENABLE_BARRETT -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_2" >> top.txt
echo "#include \"utils/arith/ntt_barrett.h\"" >> top.txt
echo "" >> top.txt
echo "" >> top.txt
cat top.txt bot.txt > ntt_barrett.c

$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="fp" -D_ENABLE_FLOATING_POINT -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_2" >> top.txt
echo "#include \"utils/arith/ntt_fp.h\"" >> top.txt
echo "" >> top.txt
echo "" >> top.txt
cat top.txt bot.txt > ntt_fp.c

$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="7681" -D_ENABLE_SOLINAS_7681 -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_2" >> top.txt
echo "#include \"utils/arith/ntt_7681.h\"" >> top.txt
echo "" >> top.txt
echo "" >> top.txt
cat top.txt bot.txt > ntt_7681.c

$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="8380417" -D_ENABLE_SOLINAS_8380417 -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_2" >> top.txt
echo "#include \"utils/arith/ntt_8380417.h\"" >> top.txt
echo "" >> top.txt
echo "" >> top.txt
cat top.txt bot.txt > ntt_8380417.c

$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="16813057" -D_ENABLE_SOLINAS_16813057 -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_2" >> top.txt
echo "#include \"utils/arith/ntt_16813057.h\"" >> top.txt
echo "" >> top.txt
echo "" >> top.txt
cat top.txt bot.txt > ntt_16813057.c

$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="134348801" -D_ENABLE_SOLINAS_134348801 -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_2" >> top.txt
echo "#include \"utils/arith/ntt_134348801.h\"" >> top.txt
echo "" >> top.txt
echo "" >> top.txt
cat top.txt bot.txt > ntt_134348801.c

$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="avx" -D_ENABLE_AVX2_INTRINSICS -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_2" >> top.txt
echo "#include \"utils/arith/ntt_avx.h\"" >> top.txt
echo "#include <immintrin.h>" >> top.txt
echo "" >> top.txt
echo "" >> top.txt
cat top.txt bot.txt > ntt_avx.c

#$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="reference_rev" -D_ENABLE_REFERENCE -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_2" >> top.txt
#echo "#include \"utils/arith/ntt_reference_rev.h\"" >> top.txt
#echo "" >> top.txt
#echo "" >> top.txt
#cat top.txt bot.txt > ntt_reference_rev.c
#
#$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="barrett_rev" -D_ENABLE_BARRETT -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_2" >> top.txt
#echo "#include \"utils/arith/ntt_barrett_rev.h\"" >> top.txt
#echo "" >> top.txt
#echo "" >> top.txt
#cat top.txt bot.txt > ntt_barrett_rev.c
#
#$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="fp_rev" -D_ENABLE_FLOATING_POINT -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_2" >> top.txt
#echo "#include \"utils/arith/ntt_fp_rev.h\"" >> top.txt
#echo "" >> top.txt
#echo "" >> top.txt
#cat top.txt bot.txt > ntt_fp_rev.c
#
#$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="7681_rev" -D_ENABLE_SOLINAS_7681 -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_2" >> top.txt
#echo "#include \"utils/arith/ntt_7681_rev.h\"" >> top.txt
#echo "" >> top.txt
#echo "" >> top.txt
#cat top.txt bot.txt > ntt_7681_rev.c
#
#$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="8380417_rev" -D_ENABLE_SOLINAS_8380417 -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_2" >> top.txt
#echo "#include \"utils/arith/ntt_8380417_rev.h\"" >> top.txt
#echo "" >> top.txt
#echo "" >> top.txt
#cat top.txt bot.txt > ntt_8380417_rev.c
#
#$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="16813057_rev" -D_ENABLE_SOLINAS_16813057 -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_2" >> top.txt
#echo "#include \"utils/arith/ntt_16813057_rev.h\"" >> top.txt
#echo "" >> top.txt
#echo "" >> top.txt
#cat top.txt bot.txt > ntt_16813057_rev.c
#
#$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="134348801_rev" -D_ENABLE_SOLINAS_134348801 -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_2" >> top.txt
#echo "#include \"utils/arith/ntt_134348801_rev.h\"" >> top.txt
#echo "" >> top.txt
#echo "" >> top.txt
#cat top.txt bot.txt > ntt_134348801_rev.c
#
#$1 -CC -P -nostdinc -E ntt_template.c.in -DNTT_NAME_EXT="avx_rev" -D_ENABLE_AVX2_INTRINSICS -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_2" >> top.txt
#echo "#include \"utils/arith/ntt_avx_rev.h\"" >> top.txt
#echo "#include <immintrin.h>" >> top.txt
#echo "" >> top.txt
#echo "" >> top.txt
#cat top.txt bot.txt > ntt_avx_rev.c


# Generate the associated header files
$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="reference" -D_ENABLE_REFERENCE -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_3" >> top.txt
cat top.txt bot.txt > ntt_reference.h

$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="barrett" -D_ENABLE_BARRETT -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_3" >> top.txt
cat top.txt bot.txt > ntt_barrett.h

$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="fp" -D_ENABLE_FLOATING_POINT -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_3" >> top.txt
cat top.txt bot.txt > ntt_fp.h

$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="7681" -D_ENABLE_SOLINAS_7681 -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_3" >> top.txt
cat top.txt bot.txt > ntt_7681.h

$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="8380417" -D_ENABLE_SOLINAS_8380417 -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_3" >> top.txt
cat top.txt bot.txt > ntt_8380417.h

$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="16813057" -D_ENABLE_SOLINAS_16813057 -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_3" >> top.txt
cat top.txt bot.txt > ntt_16813057.h

$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="134348801" -D_ENABLE_SOLINAS_134348801 -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_3" >> top.txt
cat top.txt bot.txt > ntt_134348801.h

$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="avx" -D_ENABLE_AVX2_INTRINSICS -D_NTT_MK1 -o bot.txt
echo "$file_header" > top.txt
echo "$file_header_3" >> top.txt
cat top.txt bot.txt > ntt_avx.h

#$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="reference_rev" -D_ENABLE_REFERENCE -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_3" >> top.txt
#cat top.txt bot.txt > ntt_reference_rev.h
#
#$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="barrett_rev" -D_ENABLE_BARRETT -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_3" >> top.txt
#cat top.txt bot.txt > ntt_barrett_rev.h
#
#$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="fp_rev" -D_ENABLE_FLOATING_POINT -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_3" >> top.txt
#cat top.txt bot.txt > ntt_fp_rev.h
#
#$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="7681_rev" -D_ENABLE_SOLINAS_7681 -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_3" >> top.txt
#cat top.txt bot.txt > ntt_7681_rev.h
#
#$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="8380417_rev" -D_ENABLE_SOLINAS_8380417 -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_3" >> top.txt
#cat top.txt bot.txt > ntt_8380417_rev.h
#
#$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="16813057_rev" -D_ENABLE_SOLINAS_16813057 -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_3" >> top.txt
#cat top.txt bot.txt > ntt_16813057_rev.h
#
#$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="134348801_rev" -D_ENABLE_SOLINAS_134348801 -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_3" >> top.txt
#cat top.txt bot.txt > ntt_134348801_rev.h
#
#$1 -CC -P -nostdinc -E ntt_template.h.in -DNTT_NAME_EXT="avx_rev" -D_ENABLE_AVX2_INTRINSICS -D_NTT_MK2 -o bot.txt
#echo "$file_header" > top.txt
#echo "$file_header_3" >> top.txt
#cat top.txt bot.txt > ntt_avx_rev.h

rm top.txt bot.txt
