// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace webapp {
	
	
	public partial class MasterPage {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder head;
		
		protected System.Web.UI.ScriptManager ScriptManager1;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder content;
		
		protected System.Web.UI.UpdatePanel FooterUpdatePanel;
		
		protected System.Web.UI.WebControls.Label LibVersionFooter;
	}
}
