//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapp {
	
	
	public partial class Signatures {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.DropDownList SchemeList;
		
		protected System.Web.UI.WebControls.LinkButton KeyGenBtn;
		
		protected System.Web.UI.WebControls.LinkButton KeyLoadBtn;
		
		protected System.Web.UI.WebControls.LinkButton KeySaveBtn;
		
		protected System.Web.UI.UpdatePanel UpdatePanel_Keys;
		
		protected System.Web.UI.WebControls.Label PrivKeyText;
		
		protected System.Web.UI.WebControls.Label PubKeyText;
		
		protected System.Web.UI.WebControls.LinkButton SigBtn;
		
		protected System.Web.UI.WebControls.LinkButton SigFileBtn;
		
		protected System.Web.UI.UpdatePanel UpdatePanel_Sigs;
		
		protected System.Web.UI.WebControls.Label InputText;
		
		protected System.Web.UI.WebControls.Label SignatureText;
		
		protected System.Web.UI.WebControls.Label VerBtn;
		
		protected System.Web.UI.WebControls.Label RatioTest;
		
		protected System.Web.UI.WebControls.DropDownList SigReduceList;
		
		protected System.Web.UI.WebControls.DropDownList SigSamplingList;
		
		protected System.Web.UI.WebControls.DropDownList SigCsprngList;
		
		protected System.Web.UI.WebControls.DropDownList SigEntropyList;
		
		protected System.Web.UI.WebControls.DropDownList SigHashList;
		
		protected System.Web.UI.HtmlControls.HtmlButton CfgApplyBtn;
	}
}
